#!/usr/bin/env node
// Scaffold a stochastic-image QA gate for a new agent.
//
// Generates a self-contained JavaScript file with:
//   - qaCheckSticker_<agent> function (Gemini Flash + vision, retry-on-429,
//     deterministic severity bucketing, Levenshtein softening)
//   - <agent>VisualQAStep Mastra step (id: <agent>-visual-qa, never throws)
//   - normalizeForCompare + levenshtein helpers (dependency-free)
//   - A header comment listing the workflow + publish wiring still needed
//
// Usage:
//   node scaffold-qa-gate.mjs --agent <name> --quote-step <step-id> [--output <path>]
//
// After running:
//   1. Customize the rubric items in the generated qaCheckSticker function
//      to match the agent's brand spec (colors, brandmark name, etc.)
//   2. Wire into the Mastra workflow (see references/threading.md)
//   3. Thread qaResult through agent-runner.js and publish.js
//      (see references/threading.md for the exact patches)
//
// No dependencies — runs on plain Node.js >=18.

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

function parseArgs(argv) {
  const args = { agent: null, quoteStep: null, output: null, help: false };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') args.help = true;
    else if (a === '--agent' && argv[i + 1]) { args.agent = argv[++i]; }
    else if (a === '--quote-step' && argv[i + 1]) { args.quoteStep = argv[++i]; }
    else if (a === '--output' && argv[i + 1]) { args.output = argv[++i]; }
    else { console.error(`Unknown arg: ${a}`); args.help = true; }
  }
  return args;
}

function printHelp() {
  console.log(`scaffold-qa-gate.mjs — generate boilerplate for a stochastic-image QA gate

USAGE
  node scaffold-qa-gate.mjs --agent <agent-name> --quote-step <quote-step-id> [--output <file>]

REQUIRED FLAGS
  --agent        Agent name in kebab-case, e.g. "lorignite", "stoic", "book-lover".
                 Used as the prefix for generated function/step names.
  --quote-step   The id of the upstream Mastra step that produces the expected
                 quote/text spec, e.g. "lorignite-quote", "stoic-quote".
                 The QA step pulls expectedQuote from this step's output via
                 getStepResult().

OPTIONAL FLAGS
  --output       Path to write the generated file. Defaults to stdout.

EXAMPLE
  node scaffold-qa-gate.mjs \\
    --agent ourbrand \\
    --quote-step ourbrand-quote \\
    --output frontend/lib/mastra/ourbrand-qa.js

NEXT STEPS AFTER GENERATING
  1. Edit the rubric items in qaCheckSticker_<agent> to match brand spec.
     Defaults to: letterPerfect, noDuplicates, scriptColorIsLime,
     brandmarkPresent, paletteClean — adjust per the agent's actual look.
  2. Splice the step into the agent's workflow file (see threading.md).
  3. Thread qaResult through the agent-runner factory + publishProduct.
`);
}

function camelCase(kebab) {
  return kebab.split('-').map((p, i) => i === 0 ? p : p[0].toUpperCase() + p.slice(1)).join('');
}

function pascalCase(kebab) {
  return kebab.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');
}

function generate({ agent, quoteStep }) {
  const camel = camelCase(agent);     // e.g. "ourbrand" or "bookLover"
  const pascal = pascalCase(agent);   // e.g. "Ourbrand" or "BookLover"
  const stepId = `${agent}-visual-qa`;

  return `// ${agent} agent — visual QA gate.
//
// Generated by stochastic-image-qa-gate skill scaffolder.
// Customize the rubric items below to match the agent's brand spec.
//
// WIRING TODO (see ~/.claude/skills/stochastic-image-qa-gate/references/threading.md):
//
//   1. Workflow file: import ${camel}VisualQAStep, splice into the chain
//      after generate-image-gemini via a .map step that injects expectedQuote
//      from the upstream "${quoteStep}" step:
//
//        .then(generateImageStepGemini)
//        .map(async ({ inputData, getStepResult }) => {
//          const quoteOut = getStepResult('${quoteStep}');
//          return { ...inputData, expectedQuote: quoteOut?.quote || '' };
//        })
//        .then(${camel}VisualQAStep)
//
//   2. agent-runner.js: pass qaResult to publishProduct
//        publishProduct({ ..., qaResult: imageResult.qaResult })
//
//   3. publish.js: accept qaResult, set isActive=false on kill, persist to
//      features.qa_verdict
//        const initialIsActive = qaResult?.severity === 'kill' ? false : true;

import { createStep } from '@mastra/core/workflows';
import { z } from 'zod';

// ─── Rubric schema for Gemini Flash structured JSON output ────────────────────
// Per-item: { passes: bool, issue?: string, [optional fields like renderedText] }
// Severity is computed in code from the per-item booleans, never returned by
// the model.

const QA_RUBRIC_SCHEMA = {
  type: 'OBJECT',
  properties: {
    letterPerfect: {
      type: 'OBJECT',
      properties: {
        passes: { type: 'BOOLEAN' },
        renderedText: { type: 'STRING' },
        issue: { type: 'STRING' },
      },
      required: ['passes', 'renderedText'],
    },
    noDuplicates: {
      type: 'OBJECT',
      properties: { passes: { type: 'BOOLEAN' }, issue: { type: 'STRING' } },
      required: ['passes'],
    },
    scriptColorIsLime: {
      type: 'OBJECT',
      properties: { passes: { type: 'BOOLEAN' }, issue: { type: 'STRING' } },
      required: ['passes'],
    },
    brandmarkPresent: {
      type: 'OBJECT',
      properties: { passes: { type: 'BOOLEAN' }, issue: { type: 'STRING' } },
      required: ['passes'],
    },
    paletteClean: {
      type: 'OBJECT',
      properties: { passes: { type: 'BOOLEAN' }, issue: { type: 'STRING' } },
      required: ['passes'],
    },
  },
  required: ['letterPerfect', 'noDuplicates', 'scriptColorIsLime', 'brandmarkPresent', 'paletteClean'],
};

/**
 * Send a generated sticker PNG to Gemini Flash with vision + rubric.
 * Returns { passes, severity, failures, raw }.
 *
 * CUSTOMIZE the systemPrompt below for the agent's specific brand spec —
 * colors, brandmark name, palette boundaries.
 */
export async function qaCheckSticker_${camel}(base64, expectedQuote) {
  const apiKey = process.env.GOOGLE_API_KEY;
  if (!apiKey) throw new Error('GOOGLE_API_KEY not set');

  const systemPrompt = \`You are reviewing a [BRAND_NAME] sticker before it ships to customers.
Your job is to evaluate the sticker against an explicit rubric and return JSON.
Be strict — shipped misses damage the brand.

[BRAND_NAME] BRAND SPEC:
  - Sticker fill: [PRIMARY_BG_COLOR]
  - [TYPE_TREATMENT_DESCRIPTION — e.g. "Bold sans-serif WHITE caps for non-focal words"]
  - [FOCAL_TREATMENT — e.g. "Flowing handwritten LIME GREEN cursive script for ONE focal word"]
  - Brandmark "[BRAND_NAME]" with [LOGO_DESCRIPTION] in [POSITION]
  - [BG_OUTSIDE_STICKER — e.g. "Pure white background outside the sticker"]
  - [SHAPE_SPEC — e.g. "Die-cut blob shape, irregular silhouette, not rectangle"]

RUBRIC — evaluate each item independently:

  letterPerfect: Does the rendered text on the sticker match the EXPECTED PHRASE letter-for-letter? Read every word carefully (cursive script can hide hallucinated extra letters). Set renderedText to what you actually see on the sticker. passes=true only if rendered matches expected exactly (case-insensitive, ignoring punctuation differences).

  noDuplicates: Does any word from the phrase appear more than once on the sticker? passes=true if every word from the phrase appears exactly once.

  scriptColorIsLime: Is the cursive/script focal word rendered in [FOCAL_COLOR]? It should NOT be [DISALLOWED_COLORS]. passes=true only if the script word is clearly the brand-focal color.

  brandmarkPresent: Is the word "[BRAND_NAME]" visible on the sticker (typically [POSITION])? passes=true if "[BRAND_NAME]" is legible somewhere on the sticker.

  paletteClean: Is the sticker palette restricted to [BRAND_PALETTE]? Any [OFF_BRAND_COLORS] is a fail. passes=true if palette is clean.

For any failed item, set "issue" to a one-line description of what went wrong.\`;

  const userPrompt = \`EXPECTED PHRASE on the sticker (must appear letter-perfect): "\${expectedQuote}"

Evaluate the attached sticker image against the rubric and return JSON.\`;

  const MAX_ATTEMPTS = 5;
  let res;
  let lastBody = '';
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    res = await fetch(
      \`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=\${apiKey}\`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: systemPrompt }] },
          contents: [{ parts: [
            { inlineData: { mimeType: 'image/png', data: base64 } },
            { text: userPrompt },
          ]}],
          generationConfig: {
            responseMimeType: 'application/json',
            responseSchema: QA_RUBRIC_SCHEMA,
            temperature: 0.1,
          },
        }),
      },
    );
    if (res.ok) break;
    lastBody = await res.text();
    const retriable = res.status === 429 || res.status === 503;
    if (!retriable || attempt === MAX_ATTEMPTS) {
      throw new Error(\`qaCheckSticker_${camel}: Gemini error \${res.status}: \${lastBody}\`);
    }
    const delayMs = Math.min(1000 * 2 ** (attempt - 1), 16000);
    console.warn(\`qaCheckSticker_${camel}: \${res.status} on attempt \${attempt}/\${MAX_ATTEMPTS} — backing off \${delayMs}ms\`);
    await new Promise(r => setTimeout(r, delayMs));
  }
  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
  const rubric = JSON.parse(text.replace(/\`\`\`json\\n?|\`\`\`/g, '').trim());

  // Severity is determined deterministically from the rubric JSON.
  // KILL-class: letterPerfect (with Levenshtein softening), noDuplicates, scriptColorIsLime
  // SOFT-class: brandmarkPresent, paletteClean
  const failures = [];
  let severity = 'pass';

  if (!rubric.letterPerfect?.passes) {
    const rendered = rubric.letterPerfect?.renderedText || '';
    const dist = levenshtein(normalizeForCompare(rendered), normalizeForCompare(expectedQuote));
    if (dist <= 2 && rendered.length > 0) {
      // Likely OCR misread, not a real text-rendering miss. Mark soft.
      failures.push(\`text-soft: model OCR'd "\${rendered}" vs expected "\${expectedQuote}" (Levenshtein \${dist}, likely OCR confusion)\`);
      if (severity === 'pass') severity = 'soft';
    } else {
      failures.push(\`text spelling: rendered "\${rendered || '?'}" vs expected "\${expectedQuote}" (Levenshtein \${dist}, \${rubric.letterPerfect?.issue || 'mismatch'})\`);
      severity = 'kill';
    }
  }
  if (!rubric.noDuplicates?.passes) {
    failures.push(\`duplicate words: \${rubric.noDuplicates.issue || 'detected'}\`);
    severity = 'kill';
  }
  if (!rubric.scriptColorIsLime?.passes) {
    failures.push(\`script color: \${rubric.scriptColorIsLime.issue || 'not the brand-focal color'}\`);
    severity = 'kill';
  }
  if (!rubric.brandmarkPresent?.passes) {
    failures.push(\`brandmark missing: \${rubric.brandmarkPresent.issue || 'not visible'}\`);
    if (severity === 'pass') severity = 'soft';
  }
  if (!rubric.paletteClean?.passes) {
    failures.push(\`palette: \${rubric.paletteClean.issue || 'off-brand colors detected'}\`);
    if (severity === 'pass') severity = 'soft';
  }

  return { passes: severity === 'pass', severity, failures, raw: rubric };
}

// ─── Mastra step: ${stepId} ──────────────────────────────────────────────────
// Inserted in the workflow AFTER generate-image-gemini and BEFORE the
// agent-runner factory's publishProduct call. NEVER throws — kill verdicts
// flow through to publish.js, which lands the Product as isActive=false
// (preserves evidence for review, false positives recoverable via
// admin override).

export const ${camel}VisualQAStep = createStep({
  id: '${stepId}',
  inputSchema: z.object({
    base64: z.string(),
    responseId: z.string(),
    analysis: z.any(),
    textError: z.string().nullable(),
    attempt: z.number(),
    retryFeedbacks: z.array(z.object({ attempt: z.number(), content: z.string() })),
    openaiImageRequests: z.array(z.any()),
    openaiCorrectionRequests: z.array(z.any()),
    expectedQuote: z.string(),
  }),
  outputSchema: z.object({
    base64: z.string(),
    responseId: z.string(),
    analysis: z.any(),
    textError: z.string().nullable(),
    attempt: z.number(),
    retryFeedbacks: z.array(z.object({ attempt: z.number(), content: z.string() })),
    openaiImageRequests: z.array(z.any()),
    openaiCorrectionRequests: z.array(z.any()),
    qaResult: z.any(),
  }),
  execute: async ({ inputData }) => {
    const startedAt = Date.now();
    const qa = await qaCheckSticker_${camel}(inputData.base64, inputData.expectedQuote);
    const elapsed = ((Date.now() - startedAt) / 1000).toFixed(1);

    if (qa.severity === 'kill') {
      console.warn(\`Agent (${agent} QA): KILL → publishing as inactive — \${qa.failures.join('; ')} (\${elapsed}s)\`);
    } else if (qa.severity === 'soft') {
      console.warn(\`Agent (${agent} QA): SOFT — passing through with flag — \${qa.failures.join('; ')} (\${elapsed}s)\`);
    } else {
      console.log(\`Agent (${agent} QA): PASS (\${elapsed}s)\`);
    }

    return {
      base64: inputData.base64,
      responseId: inputData.responseId,
      analysis: inputData.analysis,
      textError: inputData.textError,
      attempt: inputData.attempt,
      retryFeedbacks: inputData.retryFeedbacks,
      openaiImageRequests: inputData.openaiImageRequests,
      openaiCorrectionRequests: inputData.openaiCorrectionRequests,
      qaResult: qa,
    };
  },
});

// ─── Levenshtein helpers (dependency-free) ────────────────────────────────────

function normalizeForCompare(s) {
  return (s || '')
    .toLowerCase()
    .replace(/['‘’“”]/g, "'")
    .replace(/[^\\w\\s']/g, '')
    .replace(/\\s+/g, ' ')
    .trim();
}

function levenshtein(a, b) {
  if (a === b) return 0;
  if (!a) return b.length;
  if (!b) return a.length;
  const prev = new Array(b.length + 1);
  const curr = new Array(b.length + 1);
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    curr[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(curr[j - 1] + 1, prev[j] + 1, prev[j - 1] + cost);
    }
    for (let j = 0; j <= b.length; j++) prev[j] = curr[j];
  }
  return prev[b.length];
}
`;
}

function main() {
  const args = parseArgs(process.argv);
  if (args.help || !args.agent || !args.quoteStep) {
    printHelp();
    process.exit(args.help ? 0 : 1);
  }

  if (!/^[a-z][a-z0-9-]*$/.test(args.agent)) {
    console.error(`--agent must be kebab-case (lowercase letters, digits, hyphens). Got: ${args.agent}`);
    process.exit(1);
  }

  const code = generate({ agent: args.agent, quoteStep: args.quoteStep });

  if (args.output) {
    const dir = path.dirname(args.output);
    if (!fs.existsSync(dir)) {
      console.error(`Output directory does not exist: ${dir}`);
      process.exit(1);
    }
    fs.writeFileSync(args.output, code);
    console.log(`✓ Wrote ${args.output} (${code.length} bytes)`);
    console.log('');
    console.log('NEXT STEPS:');
    console.log('  1. Edit the rubric items in qaCheckSticker_<agent> for your brand spec');
    console.log('  2. Splice the step into your workflow file (see threading.md)');
    console.log('  3. Thread qaResult through agent-runner.js + publish.js');
  } else {
    process.stdout.write(code);
  }
}

main();
